name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker image and run
        run: |
          docker pull yourusername/yourrepo:latest
          docker run --name model_test yourusername/yourrepo:latest
          # Add command to check output score here, modify accordingly
          # Assuming test.py outputs score in a parseable way
          OUTPUT=$(docker logs model_test)
          echo "Score: $OUTPUT"
          if [[ "$OUTPUT" < "0.35" ]]; then
            echo "Insufficient Accuracy"
            exit 1
          fi
