name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Pull Docker image
        run: |
          docker login -u djamal1502 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull djamal1502/ci_cd_assignment:latest
      - name: Run Test
          docker run --name model_test djamal1502/ci_cd_assignment:latest
          # Add command to check output score here
          # Assuming test.py outputs score in a parseable way
          OUTPUT=$(docker logs model_test)
          echo "Score: $OUTPUT"
          if [[ "$OUTPUT" < "0.35" ]]; then
            echo "Insufficient Accuracy"
            exit 1
          fi
