name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image and run
        run: |
          docker pull djamal1502/ci_cd_assignment:latest
          docker run --name model_test djamal1502/ci_cd_assignment:latest
          # Add command to check output score here, modify accordingly
          # Assuming test.py outputs score in a parseable way
          OUTPUT=$(docker logs model_test)
          echo "Score: $OUTPUT"
          if [[ "$OUTPUT" < "0.35" ]]; then
            echo "Insufficient Accuracy"
            exit 1
          fi
