
name: Train

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and Push Image
        run: |
          docker login -u djamal1502 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t djamal1502/ci_cd_assignment:latest . 
          docker push djamal1502/ci_cd_assignment:latest 
      
